### ISSUE TITLE
Veel ongelezen reacties

### ISSUE THREAD

**Issue by Coldrush** [marien/coconut-chrome-extension#11]
Als er veel ongelezen reacties in het forum zijn, dan blijft het coconut-logo grijs en krijg je geen updates door.

**Comment by marien** [comment]
Versie 0.2.1 staat op de Chrome Webstore. Kun jij proberen of het nu wel goed gaat?

**Comment by Coldrush** [comment]
Euuh, nu niet, moet ik eerst weer veel reacties niet lezen, vanmorgen heb ik ze namelijk allemaal op "Gelezen" gezet.

Tips hoe ik de situatie moet nabootsen moet je maar doorgeven.

**Comment by marien** [comment]
Zaheer heeft het getest en bij hem werkt het.
