### ISSUE TITLE
Focus op reactie-invoer

### ISSUE THREAD

**Issue by Coldrush** [marien/coconut-chrome-extension#13]
Als ik op mijn dashboard de conversaties doorscroll met "J"  en een conversatie uitklap, dan zou ik verwachten direct te kunnen beginnen met het typen van mijn reactie.

Dat kan nu nog niet.

**Comment by marien** [comment]
Direct beginnen met typen is vervelend als je alleen aan het bijlezen bent. Na het uitklappen met v op enter drukken om te beginnen met typen werk prettiger.
